version: "3"

services:
  nginx:
    container_name: rr_nginx
    image: nginx:1.23.1-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/collectstatic:/static
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - rr_web

  rr_web:
    container_name: rr_web
    image: reresearch
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./data:/src/data
